name: fui_kit
description: Our library offers more than 498 vector SVG icons in 6 different styles or themes.
version: 2.0.2
homepage: https://wp.me/pd2qu8-hH
repository: https://github.com/baldomerocho/fui_kit
issue_tracker: https://github.com/baldomerocho/fui_kit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
#    my assets is shared with the app, lib/assets...
    - assets/icons/bold/rounded/svg/
    - assets/icons/bold/straight/svg/
    - assets/icons/regular/rounded/svg/
    - assets/icons/regular/straight/svg/
    - assets/icons/solid/rounded/svg/
    - assets/icons/solid/straight/svg/