class SvgIcon {
  String add;
  String addressBook;
  String alarmClock;
  String alignCenter;
  String alignJustify;
  String alignLeft;
  String alignRight;
  String ambulance;
  String angleDoubleLeft;
  String angleDoubleRight;
  String angleDoubleSmallLeft;
  String angleDoubleSmallRight;
  String angleDown;
  String angleLeft;
  String angleRight;
  String angleSmallDown;
  String angleSmallLeft;
  String angleSmallRight;
  String angleSmallUp;
  String angleUp;
  String apple;
  String appsAdd;
  String appsDelete;
  String appsSort;
  String apps;
  String archive;
  String arrowDown;
  String arrowFromBottom;
  String arrowLeft;
  String arrowRight;
  String arrowSmallDown;
  String arrowSmallLeft;
  String arrowSmallRight;
  String arrowSmallUp;
  String arrowUp;
  String asterik;
  String at;
  String backpack;
  String badge;
  String balloons;
  String ban;
  String bandAid;
  String bank;
  String barberShop;
  String baseball;
  String basketball;
  String bed;
  String beer;
  String bellRing;
  String bellSchool;
  String bell;
  String bike;
  String billiard;
  String bold;
  String bookAlt;
  String book;
  String bookmark;
  String bowling;
  String boxAlt;
  String box;
  String breadSlice;
  String briefcase;
  String broom;
  String browser;
  String brush;
  String bug;
  String building;
  String bulb;
  String butterfly;
  String cakeBirthday;
  String cakeWedding;
  String calculator;
  String calendar;
  String callHistory;
  String callIncoming;
  String callMissed;
  String callOutgoing;
  String camera;
  String camping;
  String car;
  String caretDown;
  String caretLeft;
  String caretRight;
  String caretUp;
  String carrot;
  String chartConnected;
  String chartHistogram;
  String chartNetwork;
  String chartPieAlt;
  String chartPie;
  String chartPyramid;
  String chartSetTheory;
  String chartTree;
  String chatArrowDown;
  String chatArrowGrow;
  String check;
  String checkbox;
  String cheese;
  String chessPiece;
  String childHead;
  String circleSmall;
  String circle;
  String clip;
  String clock;
  String cloudCheck;
  String cloudDisabled;
  String cloudDownload;
  String cloudShare;
  String cloudUpload;
  String cloud;
  String clouds;
  String cocktail;
  String coffee;
  String commentAlt;
  String commentCheck;
  String commentHeart;
  String commentInfo;
  String commentUser;
  String comment;
  String comments;
  String compressAlt;
  String compress;
  String computer;
  String confetti;
  String cookie;
  String copyAlt;
  String copy;
  String copyright;
  String cow;
  String cream;
  String creditCard;
  String croissant;
  String crossCircle;
  String crossSmall;
  String cross;
  String crown;
  String cube;
  String cupcake;
  String cursorFinger;
  String cursorPlus;
  String cursorTextAlt;
  String cursorText;
  String cursor;
  String dart;
  String dashboard;
  String dataTransfer;
  String database;
  String delete;
  String diamond;
  String dice;
  String diploma;
  String discoBall;
  String disk;
  String doctor;
  String documentSigned;
  String document;
  String dollar;
  String download;
  String drinkAlt;
  String drumstick;
  String duplicate;
  String eLearning;
  String earnings;
  String editAlt;
  String edit;
  String envelopeBan;
  String envelopeDownload;
  String envelopeMarker;
  String envelopeOpen;
  String envelopePlus;
  String envelope;
  String euro;
  String exclamation;
  String expand;
  String eyeCrossed;
  String eyeDropper;
  String eye;
  String feather;
  String ferrisWheel;
  String fileAdd;
  String fileAi;
  String fileCheck;
  String fileDelete;
  String fileEps;
  String fileGif;
  String fileMusic;
  String filePsd;
  String file;
  String fill;
  String film;
  String filter;
  String fingerprint;
  String fish;
  String flag;
  String flame;
  String flipHorizontal;
  String flowerBouquet;
  String flowerTulip;
  String flower;
  String folderAdd;
  String folder;
  String following;
  String football;
  String form;
  String forward;
  String fox;
  String frown;
  String ftp;
  String gallery;
  String gamepad;
  String gasPump;
  String gem;
  String gift;
  String glassCheers;
  String glasses;
  String globeAlt;
  String globe;
  String golf;
  String graduationCap;
  String graphicTablet;
  String gridAlt;
  String grid;
  String guitar;
  String gym;
  String hamburger;
  String handHoldingHeart;
  String hastag;
  String hatBirthday;
  String headSideThinking;
  String headphones;
  String headset;
  String heartArrow;
  String heart;
  String homeLocationAlt;
  String homeLocation;
  String home;
  String hourglassEnd;
  String hourglass;
  String iceCream;
  String iceSkate;
  String idBadge;
  String inbox;
  String incognito;
  String indent;
  String infinity;
  String info;
  String interactive;
  String interlining;
  String interrogation;
  String italic;
  String jpg;
  String key;
  String keyboard;
  String kite;
  String label;
  String laptop;
  String lasso;
  String laugh;
  String layers;
  String layoutFluid;
  String leaf;
  String letterCase;
  String lifeRing;
  String lineWidth;
  String link;
  String lipstick;
  String listCheck;
  String list;
  String locationAlt;
  String lockAlt;
  String lock;
  String luggageRolling;
  String magicWand;
  String makeupBrush;
  String manHead;
  String mapMarkerCross;
  String mapMarkerHome;
  String mapMarkerMinus;
  String mapMarkerPlus;
  String mapMarker;
  String map;
  String markerTime;
  String marker;
  String marsDouble;
  String mars;
  String maskCarnival;
  String medicine;
  String megaphone;
  String meh;
  String menuBurger;
  String menuDotsVertical;
  String menuDots;
  String microphoneAlt;
  String microphone;
  String minusSmall;
  String minus;
  String mobile;
  String modeLandscape;
  String modePortrait;
  String money;
  String moon;
  String mountains;
  String mouse;
  String mugAlt;
  String musicAlt;
  String music;
  String navigation;
  String networkCloud;
  String network;
  String notebook;
  String opacity;
  String package;
  String paintBrush;
  String palette;
  String paperPlane;
  String password;
  String pause;
  String paw;
  String pencil;
  String pharmacy;
  String phoneCall;
  String phoneCross;
  String phonePause;
  String phoneSlash;
  String physics;
  String picture;
  String pingPong;
  String pizzaSlice;
  String plane;
  String playAlt;
  String play;
  String playingCards;
  String plusSmall;
  String plus;
  String pokerChip;
  String portrait;
  String pound;
  String power;
  String presentation;
  String print;
  String protractor;
  String pulse;
  String pyramid;
  String quoteRight;
  String rainbow;
  String raindrops;
  String rec;
  String receipt;
  String recordVinyl;
  String rectabgleVertical;
  String rectangleHorizontal;
  String rectanglePanoramic;
  String recycle;
  String redoAlt;
  String redo;
  String reflect;
  String refresh;
  String resize;
  String resources;
  String rewind;
  String rhombus;
  String ringsWedding;
  String road;
  String rocket;
  String roomService;
  String rotateRight;
  String rugby;
  String sad;
  String salad;
  String scale;
  String schoolBus;
  String school;
  String scissors;
  String screen;
  String searchAlt;
  String searchHeart;
  String search;
  String settingsSliders;
  String settings;
  String share;
  String shieldCheck;
  String shieldExclamation;
  String shieldInterrogation;
  String shieldPlus;
  String shield;
  String shipSide;
  String ship;
  String shop;
  String shoppingBagAdd;
  String shoppingBag;
  String shoppingCartAdd;
  String shoppingCartCheck;
  String shoppingCart;
  String shuffle;
  String signInAlt;
  String signIn;
  String signOutAlt;
  String signOut;
  String signalAlt1;
  String signalAlt2;
  String signalAlt;
  String skateboard;
  String smartphone;
  String smileWink;
  String smile;
  String snowflake;
  String soap;
  String soup;
  String spa;
  String speaker;
  String sphere;
  String spinnerAlt;
  String spinner;
  String squareRoot;
  String square;
  String starOctogram;
  String star;
  String stats;
  String stethoscope;
  String sticker;
  String stop;
  String stopwatch;
  String subtitles;
  String sun;
  String sunrise;
  String surfing;
  String sword;
  String syringe;
  String tablet;
  String target;
  String taxi;
  String tennis;
  String terrace;
  String testTube;
  String test;
  String textCheck;
  String text;
  String thermometerHalf;
  String thumbsDown;
  String thumbsUp;
  String thumbtack;
  String ticket;
  String timeAdd;
  String timeCheck;
  String timeDelete;
  String timeFast;
  String timeForwardSixty;
  String timeForwardTen;
  String timeForward;
  String timeHalfPast;
  String timeOclock;
  String timePast;
  String timeQuarterPast;
  String timeQuarterTo;
  String timeTwentyFour;
  String toolCrop;
  String toolMarquee;
  String tooth;
  String tornado;
  String trainSide;
  String train;
  String transform;
  String trash;
  String treatment;
  String treeChristmas;
  String tree;
  String triangle;
  String trophy;
  String truckSide;
  String umbrella;
  String underline;
  String undoAlt;
  String undo;
  String unlock;
  String upload;
  String usbPendrive;
  String userAdd;
  String userDelete;
  String userRemove;
  String userTime;
  String user;
  String utensils;
  String vectorAlt;
  String vector;
  String venusDouble;
  String venusMars;
  String venus;
  String videoCamera;
  String volleyball;
  String volume;
  String wheelchair;
  String wifiAlt;
  String wind;
  String womanHead;
  String world;
  String yen;
  String zoomIn;
  String zoomOut;

  SvgIcon(
      {required this.add,
      required this.addressBook,
      required this.alarmClock,
      required this.alignCenter,
      required this.alignJustify,
      required this.alignLeft,
      required this.alignRight,
      required this.ambulance,
      required this.angleDoubleLeft,
      required this.angleDoubleRight,
      required this.angleDoubleSmallLeft,
      required this.angleDoubleSmallRight,
      required this.angleDown,
      required this.angleLeft,
      required this.angleRight,
      required this.angleSmallDown,
      required this.angleSmallLeft,
      required this.angleSmallRight,
      required this.angleSmallUp,
      required this.angleUp,
      required this.apple,
      required this.appsAdd,
      required this.appsDelete,
      required this.appsSort,
      required this.apps,
      required this.archive,
      required this.arrowDown,
      required this.arrowFromBottom,
      required this.arrowLeft,
      required this.arrowRight,
      required this.arrowSmallDown,
      required this.arrowSmallLeft,
      required this.arrowSmallRight,
      required this.arrowSmallUp,
      required this.arrowUp,
      required this.asterik,
      required this.at,
      required this.backpack,
      required this.badge,
      required this.balloons,
      required this.ban,
      required this.bandAid,
      required this.bank,
      required this.barberShop,
      required this.baseball,
      required this.basketball,
      required this.bed,
      required this.beer,
      required this.bellRing,
      required this.bellSchool,
      required this.bell,
      required this.bike,
      required this.billiard,
      required this.bold,
      required this.bookAlt,
      required this.book,
      required this.bookmark,
      required this.bowling,
      required this.boxAlt,
      required this.box,
      required this.breadSlice,
      required this.briefcase,
      required this.broom,
      required this.browser,
      required this.brush,
      required this.bug,
      required this.building,
      required this.bulb,
      required this.butterfly,
      required this.cakeBirthday,
      required this.cakeWedding,
      required this.calculator,
      required this.calendar,
      required this.callHistory,
      required this.callIncoming,
      required this.callMissed,
      required this.callOutgoing,
      required this.camera,
      required this.camping,
      required this.car,
      required this.caretDown,
      required this.caretLeft,
      required this.caretRight,
      required this.caretUp,
      required this.carrot,
      required this.chartConnected,
      required this.chartHistogram,
      required this.chartNetwork,
      required this.chartPieAlt,
      required this.chartPie,
      required this.chartPyramid,
      required this.chartSetTheory,
      required this.chartTree,
      required this.chatArrowDown,
      required this.chatArrowGrow,
      required this.check,
      required this.checkbox,
      required this.cheese,
      required this.chessPiece,
      required this.childHead,
      required this.circleSmall,
      required this.circle,
      required this.clip,
      required this.clock,
      required this.cloudCheck,
      required this.cloudDisabled,
      required this.cloudDownload,
      required this.cloudShare,
      required this.cloudUpload,
      required this.cloud,
      required this.clouds,
      required this.cocktail,
      required this.coffee,
      required this.commentAlt,
      required this.commentCheck,
      required this.commentHeart,
      required this.commentInfo,
      required this.commentUser,
      required this.comment,
      required this.comments,
      required this.compressAlt,
      required this.compress,
      required this.computer,
      required this.confetti,
      required this.cookie,
      required this.copyAlt,
      required this.copy,
      required this.copyright,
      required this.cow,
      required this.cream,
      required this.creditCard,
      required this.croissant,
      required this.crossCircle,
      required this.crossSmall,
      required this.cross,
      required this.crown,
      required this.cube,
      required this.cupcake,
      required this.cursorFinger,
      required this.cursorPlus,
      required this.cursorTextAlt,
      required this.cursorText,
      required this.cursor,
      required this.dart,
      required this.dashboard,
      required this.dataTransfer,
      required this.database,
      required this.delete,
      required this.diamond,
      required this.dice,
      required this.diploma,
      required this.discoBall,
      required this.disk,
      required this.doctor,
      required this.documentSigned,
      required this.document,
      required this.dollar,
      required this.download,
      required this.drinkAlt,
      required this.drumstick,
      required this.duplicate,
      required this.eLearning,
      required this.earnings,
      required this.editAlt,
      required this.edit,
      required this.envelopeBan,
      required this.envelopeDownload,
      required this.envelopeMarker,
      required this.envelopeOpen,
      required this.envelopePlus,
      required this.envelope,
      required this.euro,
      required this.exclamation,
      required this.expand,
      required this.eyeCrossed,
      required this.eyeDropper,
      required this.eye,
      required this.feather,
      required this.ferrisWheel,
      required this.fileAdd,
      required this.fileAi,
      required this.fileCheck,
      required this.fileDelete,
      required this.fileEps,
      required this.fileGif,
      required this.fileMusic,
      required this.filePsd,
      required this.file,
      required this.fill,
      required this.film,
      required this.filter,
      required this.fingerprint,
      required this.fish,
      required this.flag,
      required this.flame,
      required this.flipHorizontal,
      required this.flowerBouquet,
      required this.flowerTulip,
      required this.flower,
      required this.folderAdd,
      required this.folder,
      required this.following,
      required this.football,
      required this.form,
      required this.forward,
      required this.fox,
      required this.frown,
      required this.ftp,
      required this.gallery,
      required this.gamepad,
      required this.gasPump,
      required this.gem,
      required this.gift,
      required this.glassCheers,
      required this.glasses,
      required this.globeAlt,
      required this.globe,
      required this.golf,
      required this.graduationCap,
      required this.graphicTablet,
      required this.gridAlt,
      required this.grid,
      required this.guitar,
      required this.gym,
      required this.hamburger,
      required this.handHoldingHeart,
      required this.hastag,
      required this.hatBirthday,
      required this.headSideThinking,
      required this.headphones,
      required this.headset,
      required this.heartArrow,
      required this.heart,
      required this.homeLocationAlt,
      required this.homeLocation,
      required this.home,
      required this.hourglassEnd,
      required this.hourglass,
      required this.iceCream,
      required this.iceSkate,
      required this.idBadge,
      required this.inbox,
      required this.incognito,
      required this.indent,
      required this.infinity,
      required this.info,
      required this.interactive,
      required this.interlining,
      required this.interrogation,
      required this.italic,
      required this.jpg,
      required this.key,
      required this.keyboard,
      required this.kite,
      required this.label,
      required this.laptop,
      required this.lasso,
      required this.laugh,
      required this.layers,
      required this.layoutFluid,
      required this.leaf,
      required this.letterCase,
      required this.lifeRing,
      required this.lineWidth,
      required this.link,
      required this.lipstick,
      required this.listCheck,
      required this.list,
      required this.locationAlt,
      required this.lockAlt,
      required this.lock,
      required this.luggageRolling,
      required this.magicWand,
      required this.makeupBrush,
      required this.manHead,
      required this.mapMarkerCross,
      required this.mapMarkerHome,
      required this.mapMarkerMinus,
      required this.mapMarkerPlus,
      required this.mapMarker,
      required this.map,
      required this.markerTime,
      required this.marker,
      required this.marsDouble,
      required this.mars,
      required this.maskCarnival,
      required this.medicine,
      required this.megaphone,
      required this.meh,
      required this.menuBurger,
      required this.menuDotsVertical,
      required this.menuDots,
      required this.microphoneAlt,
      required this.microphone,
      required this.minusSmall,
      required this.minus,
      required this.mobile,
      required this.modeLandscape,
      required this.modePortrait,
      required this.money,
      required this.moon,
      required this.mountains,
      required this.mouse,
      required this.mugAlt,
      required this.musicAlt,
      required this.music,
      required this.navigation,
      required this.networkCloud,
      required this.network,
      required this.notebook,
      required this.opacity,
      required this.package,
      required this.paintBrush,
      required this.palette,
      required this.paperPlane,
      required this.password,
      required this.pause,
      required this.paw,
      required this.pencil,
      required this.pharmacy,
      required this.phoneCall,
      required this.phoneCross,
      required this.phonePause,
      required this.phoneSlash,
      required this.physics,
      required this.picture,
      required this.pingPong,
      required this.pizzaSlice,
      required this.plane,
      required this.playAlt,
      required this.play,
      required this.playingCards,
      required this.plusSmall,
      required this.plus,
      required this.pokerChip,
      required this.portrait,
      required this.pound,
      required this.power,
      required this.presentation,
      required this.print,
      required this.protractor,
      required this.pulse,
      required this.pyramid,
      required this.quoteRight,
      required this.rainbow,
      required this.raindrops,
      required this.rec,
      required this.receipt,
      required this.recordVinyl,
      required this.rectabgleVertical,
      required this.rectangleHorizontal,
      required this.rectanglePanoramic,
      required this.recycle,
      required this.redoAlt,
      required this.redo,
      required this.reflect,
      required this.refresh,
      required this.resize,
      required this.resources,
      required this.rewind,
      required this.rhombus,
      required this.ringsWedding,
      required this.road,
      required this.rocket,
      required this.roomService,
      required this.rotateRight,
      required this.rugby,
      required this.sad,
      required this.salad,
      required this.scale,
      required this.schoolBus,
      required this.school,
      required this.scissors,
      required this.screen,
      required this.searchAlt,
      required this.searchHeart,
      required this.search,
      required this.settingsSliders,
      required this.settings,
      required this.share,
      required this.shieldCheck,
      required this.shieldExclamation,
      required this.shieldInterrogation,
      required this.shieldPlus,
      required this.shield,
      required this.shipSide,
      required this.ship,
      required this.shop,
      required this.shoppingBagAdd,
      required this.shoppingBag,
      required this.shoppingCartAdd,
      required this.shoppingCartCheck,
      required this.shoppingCart,
      required this.shuffle,
      required this.signInAlt,
      required this.signIn,
      required this.signOutAlt,
      required this.signOut,
      required this.signalAlt1,
      required this.signalAlt2,
      required this.signalAlt,
      required this.skateboard,
      required this.smartphone,
      required this.smileWink,
      required this.smile,
      required this.snowflake,
      required this.soap,
      required this.soup,
      required this.spa,
      required this.speaker,
      required this.sphere,
      required this.spinnerAlt,
      required this.spinner,
      required this.squareRoot,
      required this.square,
      required this.starOctogram,
      required this.star,
      required this.stats,
      required this.stethoscope,
      required this.sticker,
      required this.stop,
      required this.stopwatch,
      required this.subtitles,
      required this.sun,
      required this.sunrise,
      required this.surfing,
      required this.sword,
      required this.syringe,
      required this.tablet,
      required this.target,
      required this.taxi,
      required this.tennis,
      required this.terrace,
      required this.testTube,
      required this.test,
      required this.textCheck,
      required this.text,
      required this.thermometerHalf,
      required this.thumbsDown,
      required this.thumbsUp,
      required this.thumbtack,
      required this.ticket,
      required this.timeAdd,
      required this.timeCheck,
      required this.timeDelete,
      required this.timeFast,
      required this.timeForwardSixty,
      required this.timeForwardTen,
      required this.timeForward,
      required this.timeHalfPast,
      required this.timeOclock,
      required this.timePast,
      required this.timeQuarterPast,
      required this.timeQuarterTo,
      required this.timeTwentyFour,
      required this.toolCrop,
      required this.toolMarquee,
      required this.tooth,
      required this.tornado,
      required this.trainSide,
      required this.train,
      required this.transform,
      required this.trash,
      required this.treatment,
      required this.treeChristmas,
      required this.tree,
      required this.triangle,
      required this.trophy,
      required this.truckSide,
      required this.umbrella,
      required this.underline,
      required this.undoAlt,
      required this.undo,
      required this.unlock,
      required this.upload,
      required this.usbPendrive,
      required this.userAdd,
      required this.userDelete,
      required this.userRemove,
      required this.userTime,
      required this.user,
      required this.utensils,
      required this.vectorAlt,
      required this.vector,
      required this.venusDouble,
      required this.venusMars,
      required this.venus,
      required this.videoCamera,
      required this.volleyball,
      required this.volume,
      required this.wheelchair,
      required this.wifiAlt,
      required this.wind,
      required this.womanHead,
      required this.world,
      required this.yen,
      required this.zoomIn,
      required this.zoomOut});
}
